version: '3.8'

services:
  # Наш сервер
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - elevator-net

  # Наш React додаток
  frontend:
    build: ./my-elevator-react
    ports:
      - "5173:5173"
    networks:
      - elevator-net
    depends_on:
      - backend

networks:
  elevator-net:
    driver: bridge